<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use TCG\Voyager\Models\DataRow;
use TCG\Voyager\Models\DataType;

class DataRowsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Correo Electrónico',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 3,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Constraseña',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => 'null',
                'order' => 4,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Token de Recuerdo',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 5,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 6,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 7,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 8,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Rol',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '"{\\"model\\":\\"TCG\\\\\\\\Voyager\\\\\\\\Models\\\\\\\\Role\\",\\"table\\":\\"roles\\",\\"type\\":\\"belongsTo\\",\\"column\\":\\"role_id\\",\\"key\\":\\"id\\",\\"label\\":\\"display_name\\",\\"pivot_table\\":\\"roles\\",\\"pivot\\":0}"',
                'order' => 10,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '"{\\"model\\":\\"TCG\\\\\\\\Voyager\\\\\\\\Models\\\\\\\\Role\\",\\"table\\":\\"roles\\",\\"type\\":\\"belongsToMany\\",\\"column\\":\\"id\\",\\"key\\":\\"id\\",\\"label\\":\\"display_name\\",\\"pivot_table\\":\\"user_roles\\",\\"pivot\\":\\"1\\",\\"taggable\\":\\"0\\"}"',
                'order' => 11,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 12,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => 'null',
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Nombre a Mostrar',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Rol',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => 'null',
                'order' => 9,
            ),
            21 => 
            array (
                'id' => 85,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 86,
                'data_type_id' => 13,
                'field' => 'user_type',
                'type' => 'text',
                'display_name' => 'User Type',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 2,
            ),
            23 => 
            array (
                'id' => 87,
                'data_type_id' => 13,
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 3,
            ),
            24 => 
            array (
                'id' => 88,
                'data_type_id' => 13,
                'field' => 'event',
                'type' => 'text',
                'display_name' => 'Event',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 4,
            ),
            25 => 
            array (
                'id' => 89,
                'data_type_id' => 13,
                'field' => 'auditable_type',
                'type' => 'text',
                'display_name' => 'Auditable Type',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 5,
            ),
            26 => 
            array (
                'id' => 90,
                'data_type_id' => 13,
                'field' => 'auditable_id',
                'type' => 'text',
                'display_name' => 'Auditable Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 6,
            ),
            27 => 
            array (
                'id' => 91,
                'data_type_id' => 13,
                'field' => 'old_values',
                'type' => 'text',
                'display_name' => 'Old Values',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 7,
            ),
            28 => 
            array (
                'id' => 92,
                'data_type_id' => 13,
                'field' => 'new_values',
                'type' => 'text',
                'display_name' => 'New Values',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 8,
            ),
            29 => 
            array (
                'id' => 93,
                'data_type_id' => 13,
                'field' => 'url',
                'type' => 'text',
                'display_name' => 'Url',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 9,
            ),
            30 => 
            array (
                'id' => 94,
                'data_type_id' => 13,
                'field' => 'ip_address',
                'type' => 'text',
                'display_name' => 'Ip Address',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 10,
            ),
            31 => 
            array (
                'id' => 95,
                'data_type_id' => 13,
                'field' => 'user_agent',
                'type' => 'text',
                'display_name' => 'User Agent',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 11,
            ),
            32 => 
            array (
                'id' => 96,
                'data_type_id' => 13,
                'field' => 'tags',
                'type' => 'text',
                'display_name' => 'Tags',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 12,
            ),
            33 => 
            array (
                'id' => 97,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 13,
            ),
            34 => 
            array (
                'id' => 98,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '"\\"{}\\""',
                'order' => 14,
            ),
            35 => 
            array (
                'id' => 99,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            36 => 
            array (
                'id' => 100,
                'data_type_id' => 14,
                'field' => 'parent_id',
                'type' => 'select_dropdown',
                'display_name' => 'Padre',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"","null":"","options":{"":"-- None --"},"relationship":{"key":"id","label":"name"}}',
                'order' => 2,
            ),
            37 => 
            array (
                'id' => 101,
                'data_type_id' => 14,
                'field' => 'order',
                'type' => 'text',
                'display_name' => 'Orden',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":1}',
                'order' => 3,
            ),
            38 => 
            array (
                'id' => 102,
                'data_type_id' => 14,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Nombre',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            39 => 
            array (
                'id' => 103,
                'data_type_id' => 14,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"name"}}',
                'order' => 5,
            ),
            40 => 
            array (
                'id' => 104,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            41 => 
            array (
                'id' => 105,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            42 => 
            array (
                'id' => 106,
                'data_type_id' => 15,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            43 => 
            array (
                'id' => 107,
                'data_type_id' => 15,
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Autor',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            44 => 
            array (
                'id' => 108,
                'data_type_id' => 15,
                'field' => 'category_id',
                'type' => 'text',
                'display_name' => 'Categoría',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            45 => 
            array (
                'id' => 109,
                'data_type_id' => 15,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            46 => 
            array (
                'id' => 110,
                'data_type_id' => 15,
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Extracto',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            47 => 
            array (
                'id' => 111,
                'data_type_id' => 15,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Cuerpo',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 6,
            ),
            48 => 
            array (
                'id' => 112,
                'data_type_id' => 15,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagen del Post',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => 7,
            ),
            49 => 
            array (
                'id' => 113,
                'data_type_id' => 15,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title","forceUpdate":true},"validation":{"rule":"unique:posts,slug"}}',
                'order' => 8,
            ),
            50 => 
            array (
                'id' => 114,
                'data_type_id' => 15,
                'field' => 'meta_description',
                'type' => 'text_area',
                'display_name' => 'Meta Descripción',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 9,
            ),
            51 => 
            array (
                'id' => 115,
                'data_type_id' => 15,
                'field' => 'meta_keywords',
                'type' => 'text_area',
                'display_name' => 'Meta Palabras Clave',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 10,
            ),
            52 => 
            array (
                'id' => 116,
                'data_type_id' => 15,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Estatus',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'order' => 11,
            ),
            53 => 
            array (
                'id' => 117,
                'data_type_id' => 15,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 12,
            ),
            54 => 
            array (
                'id' => 118,
                'data_type_id' => 15,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 13,
            ),
            55 => 
            array (
                'id' => 119,
                'data_type_id' => 15,
                'field' => 'seo_title',
                'type' => 'text',
                'display_name' => 'Título SEO',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 14,
            ),
            56 => 
            array (
                'id' => 120,
                'data_type_id' => 15,
                'field' => 'featured',
                'type' => 'checkbox',
                'display_name' => 'Destacado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 15,
            ),
            57 => 
            array (
                'id' => 121,
                'data_type_id' => 16,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            58 => 
            array (
                'id' => 122,
                'data_type_id' => 16,
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Autor',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 2,
            ),
            59 => 
            array (
                'id' => 123,
                'data_type_id' => 16,
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Título',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 3,
            ),
            60 => 
            array (
                'id' => 124,
                'data_type_id' => 16,
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Extracto',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 4,
            ),
            61 => 
            array (
                'id' => 125,
                'data_type_id' => 16,
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Cuerpo',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            62 => 
            array (
                'id' => 126,
                'data_type_id' => 16,
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"slugify":{"origin":"title"},"validation":{"rule":"unique:pages,slug"}}',
                'order' => 6,
            ),
            63 => 
            array (
                'id' => 127,
                'data_type_id' => 16,
                'field' => 'meta_description',
                'type' => 'text',
                'display_name' => 'Meta Descripción',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 7,
            ),
            64 => 
            array (
                'id' => 128,
                'data_type_id' => 16,
                'field' => 'meta_keywords',
                'type' => 'text',
                'display_name' => 'Meta Palabras Clave',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 8,
            ),
            65 => 
            array (
                'id' => 129,
                'data_type_id' => 16,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Estatus',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}',
                'order' => 9,
            ),
            66 => 
            array (
                'id' => 130,
                'data_type_id' => 16,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Creado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 10,
            ),
            67 => 
            array (
                'id' => 131,
                'data_type_id' => 16,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Actualizado',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 11,
            ),
            68 => 
            array (
                'id' => 132,
                'data_type_id' => 16,
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Imagen de la página',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 12,
            ),
            69 => 
            array (
                'id' => 133,
                'data_type_id' => 24,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            70 => 
            array (
                'id' => 134,
                'data_type_id' => 24,
                'field' => 'persona_id',
                'type' => 'text',
                'display_name' => 'Persona Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            71 => 
            array (
                'id' => 135,
                'data_type_id' => 24,
                'field' => 'mst_tipo_dic_id',
                'type' => 'text',
                'display_name' => 'Mst Tipo Dic Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            72 => 
            array (
                'id' => 136,
                'data_type_id' => 24,
                'field' => 'titulo',
                'type' => 'text',
                'display_name' => 'Titulo',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            73 => 
            array (
                'id' => 137,
                'data_type_id' => 24,
                'field' => 'descripcion',
                'type' => 'text',
                'display_name' => 'Descripcion',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            74 => 
            array (
                'id' => 138,
                'data_type_id' => 24,
                'field' => 'letra_grupo',
                'type' => 'text',
                'display_name' => 'Letra Grupo',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            75 => 
            array (
                'id' => 139,
                'data_type_id' => 24,
                'field' => 'mst_nivel_estudios_id',
                'type' => 'text',
                'display_name' => 'Mst Nivel Estudios Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            76 => 
            array (
                'id' => 140,
                'data_type_id' => 24,
                'field' => 'mst_area_materia_id',
                'type' => 'text',
                'display_name' => 'Mst Area Materia Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            77 => 
            array (
                'id' => 141,
                'data_type_id' => 24,
                'field' => 'mst_ensenanza_id',
                'type' => 'text',
                'display_name' => 'Mst Ensenanza Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            78 => 
            array (
                'id' => 142,
                'data_type_id' => 24,
                'field' => 'ano_ini_curso_escolar',
                'type' => 'text',
                'display_name' => 'Ano Ini Curso Escolar',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            79 => 
            array (
                'id' => 143,
                'data_type_id' => 24,
                'field' => 'max_acepciones_entrada',
                'type' => 'text',
                'display_name' => 'Max Acepciones Entrada',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            80 => 
            array (
                'id' => 144,
                'data_type_id' => 24,
                'field' => 'codigo',
                'type' => 'text',
                'display_name' => 'Codigo',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            81 => 
            array (
                'id' => 145,
                'data_type_id' => 24,
                'field' => 'visible_estudiante',
                'type' => 'text',
                'display_name' => 'Visible Estudiante',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 13,
            ),
            82 => 
            array (
                'id' => 146,
                'data_type_id' => 24,
                'field' => 'envios_habilitados',
                'type' => 'text',
                'display_name' => 'Envios Habilitados',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 14,
            ),
            83 => 
            array (
                'id' => 147,
                'data_type_id' => 24,
                'field' => 'envios_fecha_ini',
                'type' => 'text',
                'display_name' => 'Envios Fecha Ini',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 15,
            ),
            84 => 
            array (
                'id' => 148,
                'data_type_id' => 24,
                'field' => 'envios_fecha_fin',
                'type' => 'text',
                'display_name' => 'Envios Fecha Fin',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            85 => 
            array (
                'id' => 149,
                'data_type_id' => 24,
                'field' => 'estado',
                'type' => 'text',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 17,
            ),
            86 => 
            array (
                'id' => 150,
                'data_type_id' => 24,
                'field' => 'comentarios_visibles',
                'type' => 'text',
                'display_name' => 'Comentarios Visibles',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            87 => 
            array (
                'id' => 151,
                'data_type_id' => 24,
                'field' => 'comentarios_visibles_anteriores_a',
                'type' => 'text',
                'display_name' => 'Comentarios Visibles Anteriores A',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            88 => 
            array (
                'id' => 152,
                'data_type_id' => 24,
                'field' => 'pautas_maestras',
                'type' => 'text',
                'display_name' => 'Pautas Maestras',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            89 => 
            array (
                'id' => 153,
                'data_type_id' => 24,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 21,
            ),
            90 => 
            array (
                'id' => 154,
                'data_type_id' => 24,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 22,
            ),
            91 => 
            array (
                'id' => 155,
                'data_type_id' => 24,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 23,
            ),
            92 => 
            array (
                'id' => 156,
                'data_type_id' => 24,
                'field' => 'vigencia',
                'type' => 'text',
                'display_name' => 'Vigencia',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 24,
            ),
            93 => 
            array (
                'id' => 157,
                'data_type_id' => 26,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            94 => 
            array (
                'id' => 158,
                'data_type_id' => 26,
                'field' => 'persona_id',
                'type' => 'text',
                'display_name' => 'Persona Id',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            95 => 
            array (
                'id' => 159,
                'data_type_id' => 26,
                'field' => 'titulo',
                'type' => 'text',
                'display_name' => 'Titulo',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            96 => 
            array (
                'id' => 160,
                'data_type_id' => 26,
                'field' => 'estado',
                'type' => 'text',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            97 => 
            array (
                'id' => 161,
                'data_type_id' => 26,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            98 => 
            array (
                'id' => 162,
                'data_type_id' => 26,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            99 => 
            array (
                'id' => 163,
                'data_type_id' => 26,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
            100 => 
            array (
                'id' => 178,
                'data_type_id' => 30,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            101 => 
            array (
                'id' => 179,
                'data_type_id' => 30,
                'field' => 'cod_centro',
                'type' => 'text',
                'display_name' => 'Cod Centro',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            102 => 
            array (
                'id' => 180,
                'data_type_id' => 30,
                'field' => 'denominacion',
                'type' => 'text',
                'display_name' => 'Denominacion',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            103 => 
            array (
                'id' => 181,
                'data_type_id' => 30,
                'field' => 'estado',
                'type' => 'text',
                'display_name' => 'Estado',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            104 => 
            array (
                'id' => 182,
                'data_type_id' => 30,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 0,
                'delete' => 1,
                'details' => '{}',
                'order' => 5,
            ),
            105 => 
            array (
                'id' => 183,
                'data_type_id' => 30,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            106 => 
            array (
                'id' => 184,
                'data_type_id' => 30,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 7,
            ),
        ));
        
        
    }
}