<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuItemsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        // $dic_curso_escolar = __('voyager.dic_curso_escolar');
        // $dic_personales = __('voyager.dic_personales');
        // $centros_curso_escolar = __('voyager.centros_curso_escolar');
        $dic_curso_escolar     = 'Diccionarios curso escolar';
        $dic_personales        = 'Diccionarios personales';
        $centros_curso_escolar = 'Centros curso escolar';
        $table_name            = 'menu_items';

        try {
            $this->cleanTable($table_name);
        } catch (\Throwable $th) {
            $this->command->line("error  {$th->getMessage()}", 'info');

            throw $th;

            return;
        }

        // $this->command->line("comenzando a copiar items en  {$table_name}", 'info');
        // $insert = DB::table('menu_items')->insert([
        //     [
        //         'id'         => 1,
        //         'menu_id'    => 1,
        //         'title'      => 'Tablero',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-boat',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 1,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-04 09:41:08',
        //         'route'      => 'voyager.dashboard',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 2,
        //         'menu_id'    => 1,
        //         'title'      => 'Logs',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-warning',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 12,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'logs.view',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 3,
        //         'menu_id'    => 1,
        //         'title'      => 'Multimedia',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-images',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 5,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-04 09:41:08',
        //         'route'      => 'voyager.media.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 4,
        //         'menu_id'    => 1,
        //         'title'      => 'Roles',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-lock',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 2,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-04 09:41:08',
        //         'route'      => 'voyager.roles.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 5,
        //         'menu_id'    => 1,
        //         'title'      => 'Herramientas',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-tools',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 9,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-04 09:41:08',
        //         'route'      => '',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 6,
        //         'menu_id'    => 1,
        //         'title'      => 'Diseñador de Menús',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-list',
        //         'color'      => null,
        //         'parent_id'  => 5,
        //         'order'      => 1,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.menus.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 7,
        //         'menu_id'    => 1,
        //         'title'      => 'Base de Datos',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-data',
        //         'color'      => null,
        //         'parent_id'  => 5,
        //         'order'      => 2,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.database.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 8,
        //         'menu_id'    => 1,
        //         'title'      => 'BREAD',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-bread',
        //         'color'      => null,
        //         'parent_id'  => 5,
        //         'order'      => 4,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.bread.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 9,
        //         'menu_id'    => 1,
        //         'title'      => 'Parámetros',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-settings',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 10,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.settings.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 10,
        //         'menu_id'    => 1,
        //         'title'      => 'Vigencia',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-calendar',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 11,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'vigencia',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 11,
        //         'menu_id'    => 1,
        //         'title'      => 'Audits',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-search',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 3,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.audits.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 12,
        //         'menu_id'    => 2,
        //         'title'      => 'Logs',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-warning',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 1,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-04 09:41:08',
        //         'route'      => 'logs.view',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 13,
        //         'menu_id'    => 2,
        //         'title'      => 'Vigencia',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-calendar',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 3,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-14 11:28:37',
        //         'route'      => 'vigencia',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 14,
        //         'menu_id'    => 2,
        //         'title'      => 'Audits',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-search',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 2,
        //         'created_at' => '2022-11-04 09:41:08',
        //         'updated_at' => '2022-11-04 09:41:08',
        //         'route'      => 'voyager.audits.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 15,
        //         'menu_id'    => 1,
        //         'title'      => 'Usuarios',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-person',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 4,
        //         'created_at' => '2022-11-04 10:13:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.users.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 16,
        //         'menu_id'    => 1,
        //         'title'      => 'Compás',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-compass',
        //         'color'      => null,
        //         'parent_id'  => 5,
        //         'order'      => 3,
        //         'created_at' => '2022-11-04 10:13:08',
        //         'updated_at' => '2022-11-14 12:21:12',
        //         'route'      => 'voyager.compass.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 17,
        //         'menu_id'    => 1,
        //         'title'      => 'Categorías',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-categories',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 8,
        //         'created_at' => '2022-11-04 10:13:08',
        //         'updated_at' => '2022-11-04 10:13:08',
        //         'route'      => 'voyager.categories.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 18,
        //         'menu_id'    => 1,
        //         'title'      => 'Posts',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-news',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 6,
        //         'created_at' => '2022-11-04 10:13:08',
        //         'updated_at' => '2022-11-04 10:13:08',
        //         'route'      => 'voyager.posts.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 19,
        //         'menu_id'    => 1,
        //         'title'      => 'Páginas',
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-file-text',
        //         'color'      => null,
        //         'parent_id'  => null,
        //         'order'      => 7,
        //         'created_at' => '2022-11-04 10:13:08',
        //         'updated_at' => '2022-11-04 10:13:08',
        //         'route'      => 'voyager.pages.index',
        //         'parameters' => null,
        //     ],
        //     [
        //         'id'         => 23,
        //         'menu_id'    => 1,
        //         'title'      => $dic_curso_escolar,
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-book',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 13,
        //         'created_at' => '2022-11-15 08:58:39',
        //         'updated_at' => '2022-11-28 11:57:05',
        //         'route'      => 'voyager.dic-aulaCursoEscolar.index',
        //         'parameters' => 'null',
        //     ],
        //     [
        //         'id'         => 24,
        //         'menu_id'    => 1,
        //         'title'      => $dic_personales,
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-person',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 14,
        //         'created_at' => '2022-11-16 13:02:44',
        //         'updated_at' => '2022-11-28 11:57:05',
        //         'route'      => 'voyager.dic-personal-bread.index',
        //         'parameters' => 'null',
        //     ],
        //     [
        //         'id'         => 34,
        //         'menu_id'    => 1,
        //         'title'      => $centros_curso_escolar,
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-company',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 16,
        //         'created_at' => '2022-11-28 12:31:41',
        //         'updated_at' => '2022-12-01 07:32:39',
        //         'route'      => 'voyager.centrosBread.index',
        //         'parameters' => 'null',
        //     ],
        //     [
        //         'id'         => 21,
        //         'menu_id'    => 2,
        //         'title'      => $dic_curso_escolar,
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-book',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 4,
        //         'created_at' => '2022-11-14 13:09:40',
        //         'updated_at' => '2022-11-23 07:31:53',
        //         'route'      => 'dicsCursoEscolar',
        //         'parameters' => 'null',
        //     ],
        //     [
        //         'id'         => 25,
        //         'menu_id'    => 2,
        //         'title'      => $dic_personales,
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-person',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 5,
        //         'created_at' => '2022-11-17 08:34:54',
        //         'updated_at' => '2022-11-23 07:31:53',
        //         'route'      => 'dicsPersonales',
        //         'parameters' => 'null',
        //     ],
        //     [
        //         'id'         => 35,
        //         'menu_id'    => 2,
        //         'title'      => $centros_curso_escolar,
        //         'url'        => '',
        //         'target'     => '_self',
        //         'icon_class' => 'voyager-company',
        //         'color'      => '#000000',
        //         'parent_id'  => null,
        //         'order'      => 17,
        //         'created_at' => '2022-12-01 07:33:46',
        //         'updated_at' => '2022-12-01 07:34:06',
        //         'route'      => 'voyager.centrosBread.index',
        //         'parameters' => 'null',
        //     ],
        // ]);
        // $this->command->line("insertados items \n {$insert}", 'info');

        try {
            $this->command->line("comenzando a copiar items en  {$table_name}", 'info');
            DB::beginTransaction(); // start transaction
            $insert = DB::table('menu_items')->insert([
                [
                    'id'         => 1,
                    'menu_id'    => 1,
                    'title'      => 'Tablero',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-boat',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 1,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-04 09:41:08',
                    'route'      => 'voyager.dashboard',
                    'parameters' => null,
                ],
                [
                    'id'         => 2,
                    'menu_id'    => 1,
                    'title'      => 'Logs',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-warning',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 12,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'logs.view',
                    'parameters' => null,
                ],
                [
                    'id'         => 3,
                    'menu_id'    => 1,
                    'title'      => 'Multimedia',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-images',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 5,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-04 09:41:08',
                    'route'      => 'voyager.media.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 4,
                    'menu_id'    => 1,
                    'title'      => 'Roles',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-lock',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 2,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-04 09:41:08',
                    'route'      => 'voyager.roles.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 5,
                    'menu_id'    => 1,
                    'title'      => 'Herramientas',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-tools',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 9,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-04 09:41:08',
                    'route'      => '',
                    'parameters' => null,
                ],
                [
                    'id'         => 6,
                    'menu_id'    => 1,
                    'title'      => 'Diseñador de Menús',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-list',
                    'color'      => null,
                    'parent_id'  => 5,
                    'order'      => 1,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.menus.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 7,
                    'menu_id'    => 1,
                    'title'      => 'Base de Datos',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-data',
                    'color'      => null,
                    'parent_id'  => 5,
                    'order'      => 2,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.database.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 8,
                    'menu_id'    => 1,
                    'title'      => 'BREAD',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-bread',
                    'color'      => null,
                    'parent_id'  => 5,
                    'order'      => 4,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.bread.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 9,
                    'menu_id'    => 1,
                    'title'      => 'Parámetros',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-settings',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 10,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.settings.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 10,
                    'menu_id'    => 1,
                    'title'      => 'Vigencia',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-calendar',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 11,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'vigencia',
                    'parameters' => null,
                ],
                [
                    'id'         => 11,
                    'menu_id'    => 1,
                    'title'      => 'Audits',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-search',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 3,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.audits.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 12,
                    'menu_id'    => 2,
                    'title'      => 'Logs',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-warning',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 1,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-04 09:41:08',
                    'route'      => 'logs.view',
                    'parameters' => null,
                ],
                [
                    'id'         => 13,
                    'menu_id'    => 2,
                    'title'      => 'Vigencia',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-calendar',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 3,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-14 11:28:37',
                    'route'      => 'vigencia',
                    'parameters' => null,
                ],
                [
                    'id'         => 14,
                    'menu_id'    => 2,
                    'title'      => 'Audits',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-search',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 2,
                    'created_at' => '2022-11-04 09:41:08',
                    'updated_at' => '2022-11-04 09:41:08',
                    'route'      => 'voyager.audits.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 15,
                    'menu_id'    => 1,
                    'title'      => 'Usuarios',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-person',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 4,
                    'created_at' => '2022-11-04 10:13:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.users.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 16,
                    'menu_id'    => 1,
                    'title'      => 'Compás',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-compass',
                    'color'      => null,
                    'parent_id'  => 5,
                    'order'      => 3,
                    'created_at' => '2022-11-04 10:13:08',
                    'updated_at' => '2022-11-14 12:21:12',
                    'route'      => 'voyager.compass.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 17,
                    'menu_id'    => 1,
                    'title'      => 'Categorías',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-categories',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 8,
                    'created_at' => '2022-11-04 10:13:08',
                    'updated_at' => '2022-11-04 10:13:08',
                    'route'      => 'voyager.categories.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 18,
                    'menu_id'    => 1,
                    'title'      => 'Posts',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-news',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 6,
                    'created_at' => '2022-11-04 10:13:08',
                    'updated_at' => '2022-11-04 10:13:08',
                    'route'      => 'voyager.posts.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 19,
                    'menu_id'    => 1,
                    'title'      => 'Páginas',
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-file-text',
                    'color'      => null,
                    'parent_id'  => null,
                    'order'      => 7,
                    'created_at' => '2022-11-04 10:13:08',
                    'updated_at' => '2022-11-04 10:13:08',
                    'route'      => 'voyager.pages.index',
                    'parameters' => null,
                ],
                [
                    'id'         => 23,
                    'menu_id'    => 1,
                    'title'      => $dic_curso_escolar,
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-book',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 13,
                    'created_at' => '2022-11-15 08:58:39',
                    'updated_at' => '2022-11-28 11:57:05',
                    'route'      => 'voyager.dic-aulaCursoEscolar.index',
                    'parameters' => 'null',
                ],
                [
                    'id'         => 24,
                    'menu_id'    => 1,
                    'title'      => $dic_personales,
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-person',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 14,
                    'created_at' => '2022-11-16 13:02:44',
                    'updated_at' => '2022-11-28 11:57:05',
                    'route'      => 'voyager.dic-personal-bread.index',
                    'parameters' => 'null',
                ],
                [
                    'id'         => 34,
                    'menu_id'    => 1,
                    'title'      => $centros_curso_escolar,
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-company',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 16,
                    'created_at' => '2022-11-28 12:31:41',
                    'updated_at' => '2022-12-01 07:32:39',
                    'route'      => 'voyager.centrosBread.index',
                    'parameters' => 'null',
                ],
                [
                    'id'         => 21,
                    'menu_id'    => 2,
                    'title'      => $dic_curso_escolar,
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-book',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 4,
                    'created_at' => '2022-11-14 13:09:40',
                    'updated_at' => '2022-11-23 07:31:53',
                    'route'      => 'dicsCursoEscolar',
                    'parameters' => 'null',
                ],
                [
                    'id'         => 25,
                    'menu_id'    => 2,
                    'title'      => $dic_personales,
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-person',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 5,
                    'created_at' => '2022-11-17 08:34:54',
                    'updated_at' => '2022-11-23 07:31:53',
                    'route'      => 'dicsPersonales',
                    'parameters' => 'null',
                ],
                [
                    'id'         => 35,
                    'menu_id'    => 2,
                    'title'      => $centros_curso_escolar,
                    'url'        => '',
                    'target'     => '_self',
                    'icon_class' => 'voyager-company',
                    'color'      => '#000000',
                    'parent_id'  => null,
                    'order'      => 17,
                    'created_at' => '2022-12-01 07:33:46',
                    'updated_at' => '2022-12-01 07:34:06',
                    'route'      => 'voyager.centrosBread.index',
                    'parameters' => 'null',
                ],
                // [
                //     'id' => 30,
                //     'menu_id' => 1,
                //     'title' => 'Grabacion',
                //     'url' => '',
                //     'target' => '_self',
                //     'icon_class' => 'voyager-camera',
                //     'color' => '#000000',
                //     'parent_id' => null,
                //     'order' => 15,
                //     'created_at' => '2022-11-23 11:49:49',
                //     'updated_at' => '2022-11-28 11:57:05',
                //     'route' => 'grabacion',
                //     'parameters' => 'null',
                // ],
            ]);
            DB::commit();
            // $this->command->line("insertados items \n {$insert}", 'info');
        } catch (\Throwable $th) {
            $this->command->line('Error realizando la transaccion, se procede a hacer el rollback', 'info');
            $this->command->line($th->getMessage(), 'info');

            DB::rollBack();

            throw $th;
        }
    }

    protected function cleanupTable($table_name)
    {
        // DB::beginTransaction(); //start transaction
        try {
            DB::transaction(function () use ($table_name) {
                $this->command->line("Borrando tabla {$table_name}", 'info');
                DB::table($table_name)->delete();
            });
        } catch (\Throwable $th) {
            $this->command->line('Error realizando clean table', 'info');
            $this->command->line($th->getMessage(), 'info');

            // DB::rollBack();
            throw $th;

            return;
        }
        $this->command->line("Reseteando autoincremental de la tabla {$table_name}", 'info');
        DB::statement('SET @count = 0;');
        DB::statement("UPDATE `{$table_name}` SET `{$table_name}`.`id` = @count:= @count + 1;");
        DB::statement("ALTER TABLE `{$table_name}` AUTO_INCREMENT = 1;");
    }

    private function cleanTable($name)
    {
        try {
            $this->cleanupTable($name);
        } catch (\Throwable $th) {
            $this->command->line($th->getMessage(), 'error');

            throw $th;
        }
    }
}
