<?php

namespace Database\Seeders;

use App\Models\Voyager\PermissionRole;
// use DB;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use TCG\Voyager\Models\DataRow;
use TCG\Voyager\Models\DataType;
use TCG\Voyager\Models\Menu;
use TCG\Voyager\Models\MenuItem;
use TCG\Voyager\Models\Permission;
use TCG\Voyager\Models\Role;
use TCG\Voyager\Models\Setting;
// use Database\Seeders\VoyagerDatabaseSeeder;
use TCG\Voyager\Models\User;

class VoyagerCustomization extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Re instalación del panel de control
        $this->cleanTable('permissions');

        // $this->reinstallControlPanel();

        $this->command->line('Creando usuarios', 'info');
        $this->createUser('SuperAdmin', 'superadmin@superadmin.com', 'admin');
        $this->createUser('Oficina Técnica', 'oficinatecnica@oficinatecnica.com');

        // Permisos
        $this->cleanTable('permissions');
        $this->setPermissionsRoles();

        // Datatypes y datarows
        $this->setBreads();

        // esto ahora se crea en MenuItemsTableSeeder
        $this->cleanTable('menu_items');
        $this->cleanTable('menus');
        $this->createMenus();

        $this->setDefaultSettigns();
    }

    public function setBreads()
    {
        // Borrado de la tabla data_rows
        $this->cleanTable('data_rows');
        $this->cleanTable('data_types');

        $data_types = [
            [
                'id'                    => '1',
                'name'                  => 'users',
                'slug'                  => 'users',
                'display_name_singular' => 'Usuario',
                'display_name_plural'   => 'Usuarios',
                'icon'                  => 'voyager-person',
                'model_name'            => 'TCG\\Voyager\\Models\\User',
                'policy_name'           => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller'            => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description'           => '',
                'generate_permissions'  => '1',
                'server_side'           => '0',
                'details'               => '',
                'created_at'            => '2020-09-21 09:42:02',
                'updated_at'            => '2020-09-21 09:42:02',
            ],
            [
                'id'                    => '2',
                'name'                  => 'menus',
                'slug'                  => 'menus',
                'display_name_singular' => 'Menú',
                'display_name_plural'   => 'Menús',
                'icon'                  => 'voyager-list',
                'model_name'            => 'TCG\\Voyager\\Models\\Menu',
                'policy_name'           => null,
                'controller'            => '',
                'description'           => '',
                'generate_permissions'  => '1',
                'server_side'           => '0',
                'details'               => '',
                'created_at'            => '2020-09-21 09:42:03',
                'updated_at'            => '2020-09-21 09:42:03',
            ],
            [
                'id'                    => '3',
                'name'                  => 'roles',
                'slug'                  => 'roles',
                'display_name_singular' => 'Rol',
                'display_name_plural'   => 'Roles',
                'icon'                  => 'voyager-lock',
                'model_name'            => 'TCG\\Voyager\\Models\\Role',
                'policy_name'           => null,
                'controller'            => '',
                'description'           => '',
                'generate_permissions'  => '1',
                'server_side'           => '0',
                'details'               => '',
                'created_at'            => '2020-09-21 09:42:03',
                'updated_at'            => '2020-09-21 09:42:03',
            ],
            [
                'id'                    => '13',
                'name'                  => 'audits',
                'slug'                  => 'audits',
                'display_name_singular' => 'Audit',
                'display_name_plural'   => 'Audits',
                'icon'                  => 'voyager-search',
                'model_name'            => 'OwenIt\\Auditing\\Models\\Audit',
                'policy_name'           => null,
                'controller'            => null,
                'description'           => null,
                'generate_permissions'  => '1',
                'server_side'           => '1',
                'details'               => '{
                    "order_column":"id",
                    "order_display_column":null,
                    "order_direction":"desc",
                    "default_search_key":null
                }',
            ], [
                'id'                    => 14,
                'name'                  => 'categories',
                'slug'                  => 'categories',
                'display_name_singular' => 'Categoría',
                'display_name_plural'   => 'Categorías',
                'icon'                  => 'voyager-categories',
                'model_name'            => 'TCG\\Voyager\\Models\\Category',
                'policy_name'           => null,
                'controller'            => null,
                'description'           => null,
                'generate_permissions'  => 1,
                'server_side'           => 0,
                'details'               => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at'            => '2022-11-04 10:13:08',
                'updated_at'            => '2022-11-14 13:16:28',
            ],
            [
                'id'                    => 15,
                'name'                  => 'posts',
                'slug'                  => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural'   => 'Posts',
                'icon'                  => 'voyager-news',
                'model_name'            => 'TCG\\Voyager\\Models\\Post',
                'policy_name'           => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller'            => '',
                'description'           => '',
                'generate_permissions'  => 1,
                'server_side'           => 0,
                'details'               => '',
                'created_at'            => '2022-11-04 10:13:08',
                'updated_at'            => '2022-11-04 10:13:08',
            ],
            [
                'id'                    => 16,
                'name'                  => 'pages',
                'slug'                  => 'pages',
                'display_name_singular' => 'Página',
                'display_name_plural'   => 'Páginas',
                'icon'                  => 'voyager-file-text',
                'model_name'            => 'TCG\\Voyager\\Models\\Page',
                'policy_name'           => null,
                'controller'            => '',
                'description'           => '',
                'generate_permissions'  => 1,
                'server_side'           => 0,
                'details'               => '',
                'created_at'            => '2022-11-04 10:13:08',
                'updated_at'            => '2022-11-04 10:13:08',
            ],
            [
                'id'                    => 24,
                'name'                  => 'dic_aula',
                'slug'                  => 'dic-aulaCursoEscolar',
                'display_name_singular' => 'Dic Aula Curso Escolar',
                'display_name_plural'   => 'Dic Aulas Cursos Escolares',
                'icon'                  => 'voyager-bread',
                'model_name'            => 'App\\Models\\DicAula',
                'policy_name'           => null,
                'controller'            => 'App\\Http\\Controllers\\Voyager\\vDicAulaController',
                'description'           => null,
                'generate_permissions'  => 1,
                'server_side'           => 1,
                'details'               => '{"order_column":"ano_ini_curso_escolar","order_display_column":"ano_ini_curso_escolar","order_direction":"asc","default_search_key":"id","scope":null}',
                'created_at'            => '2022-11-15 08:58:39',
                'updated_at'            => '2022-11-15 15:54:17',
            ],
            [
                'id'                    => 26,
                'name'                  => 'dic_personal',
                'slug'                  => 'dic-personal-bread',
                'display_name_singular' => 'Diccionario personal',
                'display_name_plural'   => 'Diccionarios personales',
                'icon'                  => null,
                'model_name'            => 'App\\Models\\DiccionarioPersonal',
                'policy_name'           => null,
                'controller'            => 'App\\Http\\Controllers\\Voyager\\vDicPersonalController',
                'description'           => null,
                'generate_permissions'  => 1,
                'server_side'           => 1,
                'details'               => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at'            => '2022-11-16 13:02:44',
                'updated_at'            => '2022-11-16 13:16:23',
            ],
            [
                'id'                    => 30,
                'name'                  => 'centros',
                'slug'                  => 'centrosBread',
                'display_name_singular' => 'Centros curso escolar',
                'display_name_plural'   => 'Centros curso escolar',
                'icon'                  => null,
                'model_name'            => 'App\\Models\\Centro',
                'policy_name'           => null,
                'controller'            => 'App\\Http\\Controllers\\Voyager\\vCentrosAñoEscolarController',
                'description'           => null,
                'generate_permissions'  => 1,
                'server_side'           => 1,
                'details'               => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at'            => '2022-11-28 12:31:41',
                'updated_at'            => '2022-11-28 12:31:41',
            ],
        ];

        $this->command->line('Configurando accesos a tablas', 'info');
        foreach ($data_types as $tipo) {
            // $this->command->line("" , 'info');
            DataType::firstOrCreate(
                [
                    'id' => $tipo[
                    'id'], ],
                [
                    'name'                  => $tipo['name'],
                    'slug'                  => $tipo['slug'],
                    'display_name_singular' => $tipo['display_name_singular'],
                    'display_name_plural'   => $tipo['display_name_plural'],
                    'icon'                  => $tipo['icon'],
                    'model_name'            => $tipo['model_name'],
                    'policy_name'           => $tipo['policy_name'],
                    'controller'            => $tipo['controller'],
                    'description'           => $tipo['description'],
                    'generate_permissions'  => $tipo['generate_permissions'],
                    'server_side'           => $tipo['server_side'],
                    'details'               => $tipo['details'],
                    'created_at'            => now(),
                    'updated_at'            => now(),
                ]
            );
        }

        // Datarows
        $data_rows = [
            [
                'id'           => '1',
                'data_type_id' => '1',
                'field'        => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => '1',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '1',
            ], [
                'id'           => '2',
                'data_type_id' => '1',
                'field'        => 'name',
                'type'         => 'text',
                'display_name' => 'Nombre',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '2',
            ], [
                'id'           => '3',
                'data_type_id' => '1',
                'field'        => 'email',
                'type'         => 'text',
                'display_name' => 'Correo Electrónico',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '3',
            ], [
                'id'           => '4',
                'data_type_id' => '1',
                'field'        => 'password',
                'type'         => 'password',
                'display_name' => 'Constraseña',
                'required'     => '1',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '0',
                'details'      => '',
                'order'        => '4',
            ], [
                'id'           => '5',
                'data_type_id' => '1',
                'field'        => 'remember_token',
                'type'         => 'text',
                'display_name' => 'Token de Recuerdo',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '5',
            ], [
                'id'           => '6',
                'data_type_id' => '1',
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Creado',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '6',
            ], [
                'id'           => '7',
                'data_type_id' => '1',
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Actualizado',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '7',
            ], [
                'id'           => '8',
                'data_type_id' => '1',
                'field'        => 'avatar',
                'type'         => 'image',
                'display_name' => 'Avatar',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '8',
            ],
            [
                'id'           => 9,
                'data_type_id' => 1,
                'field'        => 'user_belongsto_role_relationship',
                'type'         => 'relationship',
                'display_name' => 'Rol',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details'      => [
                    'model'       => 'TCG\\Voyager\\Models\\Role',
                    'table'       => 'roles',
                    'type'        => 'belongsTo',
                    'column'      => 'role_id',
                    'key'         => 'id',
                    'label'       => 'display_name',
                    'pivot_table' => 'roles',
                    'pivot'       => '1',
                    'taggable'    => '0',
                ],
                'order' => 10,
            ],
            [
                'id'           => 10,
                'data_type_id' => 1,
                'field'        => 'user_belongstomany_role_relationship',
                'type'         => 'relationship',
                'display_name' => 'Roles',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details'      => [
                    'model'       => 'TCG\\Voyager\\Models\\Role',
                    'table'       => 'roles',
                    'type'        => 'belongsToMany',
                    'column'      => 'id',
                    'key'         => 'id',
                    'label'       => 'display_name',
                    'pivot_table' => 'user_roles',
                    'pivot'       => '1',
                    'taggable'    => '0',
                ],
                'order' => 11,
            ], [
                'id'           => '11',
                'data_type_id' => '1',
                'field'        => 'settings',
                'type'         => 'hidden',
                'display_name' => 'Settings',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '12',
            ], [
                'id'           => '12',
                'data_type_id' => '2',
                'field'        => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => '1',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '1',
            ], [
                'id'           => '13',
                'data_type_id' => '2',
                'field'        => 'name',
                'type'         => 'text',
                'display_name' => 'Nombre',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '2',
            ], [
                'id'           => '14',
                'data_type_id' => '2',
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Creado',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '3',
            ], [
                'id'           => '15',
                'data_type_id' => '2',
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Actualizado',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '4',
            ], [
                'id'           => '16',
                'data_type_id' => '3',
                'field'        => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => '1',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '1',
            ], [
                'id'           => '17',
                'data_type_id' => '3',
                'field'        => 'name',
                'type'         => 'text',
                'display_name' => 'Nombre',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '2',
            ], [
                'id'           => '18',
                'data_type_id' => '3',
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Creado',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '3',
            ], [
                'id'           => '19',
                'data_type_id' => '3',
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Actualizado',
                'required'     => '0',
                'browse'       => '0',
                'read'         => '0',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '4',
            ], [
                'id'           => '20',
                'data_type_id' => '3',
                'field'        => 'display_name',
                'type'         => 'text',
                'display_name' => 'Nombre a Mostrar',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '5',
            ], [
                'id'           => '21',
                'data_type_id' => '1',
                'field'        => 'role_id',
                'type'         => 'text',
                'display_name' => 'Rol_id',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '1',
                'add'          => '1',
                'delete'       => '1',
                'details'      => '',
                'order'        => '9',
            ], [
                'id'           => '85',
                'data_type_id' => '13',
                'field'        => 'id',
                'type'         => 'text',
                'display_name' => 'Id',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '1',
            ], [
                'id'           => '86',
                'data_type_id' => '13',
                'field'        => 'user_type',
                'type'         => 'text',
                'display_name' => 'User Type',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '2',
            ], [
                'id'           => '87',
                'data_type_id' => '13',
                'field'        => 'user_id',
                'type'         => 'text',
                'display_name' => 'User Id',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '3',
            ], [
                'id'           => '88',
                'data_type_id' => '13',
                'field'        => 'event',
                'type'         => 'text',
                'display_name' => 'Event',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '4',
            ], [
                'id'           => '89',
                'data_type_id' => '13',
                'field'        => 'auditable_type',
                'type'         => 'text',
                'display_name' => 'Auditable Type',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '5',
            ], [
                'id'           => '90',
                'data_type_id' => '13',
                'field'        => 'auditable_id',
                'type'         => 'text',
                'display_name' => 'Auditable Id',
                'required'     => '1',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '6',
            ], [
                'id'           => '91',
                'data_type_id' => '13',
                'field'        => 'old_values',
                'type'         => 'text',
                'display_name' => 'Old Values',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '7',
            ], [
                'id'           => '92',
                'data_type_id' => '13',
                'field'        => 'new_values',
                'type'         => 'text',
                'display_name' => 'New Values',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '8',
            ], [
                'id'           => '93',
                'data_type_id' => '13',
                'field'        => 'url',
                'type'         => 'text',
                'display_name' => 'Url',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '9',
            ], [
                'id'           => '94',
                'data_type_id' => '13',
                'field'        => 'ip_address',
                'type'         => 'text',
                'display_name' => 'Ip Address',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '10',
            ], [
                'id'           => '95',
                'data_type_id' => '13',
                'field'        => 'user_agent',
                'type'         => 'text',
                'display_name' => 'User Agent',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '11',
            ], [
                'id'           => '96',
                'data_type_id' => '13',
                'field'        => 'tags',
                'type'         => 'text',
                'display_name' => 'Tags',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '12',
            ], [
                'id'           => '97',
                'data_type_id' => '13',
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '13',
            ], [
                'id'           => '98',
                'data_type_id' => '13',
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => '0',
                'browse'       => '1',
                'read'         => '1',
                'edit'         => '0',
                'add'          => '0',
                'delete'       => '0',
                'details'      => '',
                'order'        => '14',
            ], [
                'id'           => 99,
                'data_type_id' => 14,
                'field'        => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 1,
            ],
            [
                'id'           => 100,
                'data_type_id' => 14,
                'field'        => 'parent_id',
                'type'         => 'select_dropdown',
                'display_name' => 'Padre',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"default":"","null":"","options":{"":"-- None --"},"relationship":{"key":"id","label":"name"}}',
                'order'        => 2,
            ],
            [
                'id'           => 101,
                'data_type_id' => 14,
                'field'        => 'order',
                'type'         => 'text',
                'display_name' => 'Orden',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"default":1}',
                'order'        => 3,
            ],
            [
                'id'           => 102,
                'data_type_id' => 14,
                'field'        => 'name',
                'type'         => 'text',
                'display_name' => 'Nombre',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 4,
            ],
            [
                'id'           => 103,
                'data_type_id' => 14,
                'field'        => 'slug',
                'type'         => 'text',
                'display_name' => 'Slug',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"slugify":{"origin":"name"}}',
                'order'        => 5,
            ],
            [
                'id'           => 104,
                'data_type_id' => 14,
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Creado',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 6,
            ],
            [
                'id'           => 105,
                'data_type_id' => 14,
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Actualizado',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 7,
            ],
            [
                'id'           => 106,
                'data_type_id' => 15,
                'field'        => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 1,
            ], [
                'id'           => 107,
                'data_type_id' => 15,
                'field'        => 'author_id',
                'type'         => 'text',
                'display_name' => 'Autor',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 0,
                'delete'       => 1,
                'details'      => '',
                'order'        => 2,
            ], [
                'id'           => 108,
                'data_type_id' => 15,
                'field'        => 'category_id',
                'type'         => 'text',
                'display_name' => 'Categoría',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details'      => '',
                'order'        => 3,
            ], [
                'id'           => 109,
                'data_type_id' => 15,
                'field'        => 'title',
                'type'         => 'text',
                'display_name' => 'Título',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 4,
            ], [
                'id'           => 110,
                'data_type_id' => 15,
                'field'        => 'excerpt',
                'type'         => 'text_area',
                'display_name' => 'Extracto',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 5,
            ], [
                'id'           => 111,
                'data_type_id' => 15,
                'field'        => 'body',
                'type'         => 'rich_text_box',
                'display_name' => 'Cuerpo',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 6,
            ], [
                'id'           => 112,
                'data_type_id' => 15,
                'field'        => 'image',
                'type'         => 'image',
                'display_name' => 'Imagen del Post',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order'        => 7,
            ], [
                'id'           => 113,
                'data_type_id' => 15,
                'field'        => 'slug',
                'type'         => 'text',
                'display_name' => 'Slug',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"slugify":{"origin":"title","forceUpdate":true},"validation":{"rule":"unique:posts,slug"}}',
                'order'        => 8,
            ], [
                'id'           => 114,
                'data_type_id' => 15,
                'field'        => 'meta_description',
                'type'         => 'text_area',
                'display_name' => 'Meta Descripción',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 9,
            ], [
                'id'           => 115,
                'data_type_id' => 15,
                'field'        => 'meta_keywords',
                'type'         => 'text_area',
                'display_name' => 'Meta Palabras Clave',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 10,
            ], [
                'id'           => 116,
                'data_type_id' => 15,
                'field'        => 'status',
                'type'         => 'select_dropdown',
                'display_name' => 'Estatus',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'order'        => 11,
            ], [
                'id'           => 117,
                'data_type_id' => 15,
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Creado',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 12,
            ], [
                'id'           => 118,
                'data_type_id' => 15,
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Actualizado',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 13,
            ], [
                'id'           => 119,
                'data_type_id' => 15,
                'field'        => 'seo_title',
                'type'         => 'text',
                'display_name' => 'Título SEO',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 14,
            ], [
                'id'           => 120,
                'data_type_id' => 15,
                'field'        => 'featured',
                'type'         => 'checkbox',
                'display_name' => 'Destacado',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 15,
            ], [
                'id'           => 121,
                'data_type_id' => 16,
                'field'        => 'id',
                'type'         => 'number',
                'display_name' => 'ID',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 1,
            ], [
                'id'           => 122,
                'data_type_id' => 16,
                'field'        => 'author_id',
                'type'         => 'text',
                'display_name' => 'Autor',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 2,
            ], [
                'id'           => 123,
                'data_type_id' => 16,
                'field'        => 'title',
                'type'         => 'text',
                'display_name' => 'Título',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 3,
            ], [
                'id'           => 124,
                'data_type_id' => 16,
                'field'        => 'excerpt',
                'type'         => 'text_area',
                'display_name' => 'Extracto',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 4,
            ], [
                'id'           => 125,
                'data_type_id' => 16,
                'field'        => 'body',
                'type'         => 'rich_text_box',
                'display_name' => 'Cuerpo',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 5,
            ], [
                'id'           => 126,
                'data_type_id' => 16,
                'field'        => 'slug',
                'type'         => 'text',
                'display_name' => 'Slug',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"slugify":{"origin":"title"},"validation":{"rule":"unique:pages,slug"}}',
                'order'        => 6,
            ], [
                'id'           => 127,
                'data_type_id' => 16,
                'field'        => 'meta_description',
                'type'         => 'text',
                'display_name' => 'Meta Descripción',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 7,
            ], [
                'id'           => 128,
                'data_type_id' => 16,
                'field'        => 'meta_keywords',
                'type'         => 'text',
                'display_name' => 'Meta Palabras Clave',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 8,
            ], [
                'id'           => 129,
                'data_type_id' => 16,
                'field'        => 'status',
                'type'         => 'select_dropdown',
                'display_name' => 'Estatus',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}',
                'order'        => 9,
            ], [
                'id'           => 130,
                'data_type_id' => 16,
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Creado',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 10,
            ], [
                'id'           => 131,
                'data_type_id' => 16,
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Actualizado',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 11,
            ], [
                'id'           => 132,
                'data_type_id' => 16,
                'field'        => 'image',
                'type'         => 'image',
                'display_name' => 'Imagen de la página',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 12,
            ], [
                'id'           => 133,
                'data_type_id' => 24,
                'field'        => 'id',
                'type'         => 'text',
                'display_name' => 'Id',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 1,
            ], [
                'id'           => 134,
                'data_type_id' => 24,
                'field'        => 'persona_id',
                'type'         => 'text',
                'display_name' => 'Persona Id',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 2,
            ], [
                'id'           => 135,
                'data_type_id' => 24,
                'field'        => 'mst_tipo_dic_id',
                'type'         => 'text',
                'display_name' => 'Mst Tipo Dic Id',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 3,
            ], [
                'id'           => 136,
                'data_type_id' => 24,
                'field'        => 'titulo',
                'type'         => 'text',
                'display_name' => 'Titulo',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 7,
            ], [
                'id'           => 137,
                'data_type_id' => 24,
                'field'        => 'descripcion',
                'type'         => 'text',
                'display_name' => 'Descripcion',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 8,
            ], [
                'id'           => 138,
                'data_type_id' => 24,
                'field'        => 'letra_grupo',
                'type'         => 'text',
                'display_name' => 'Letra Grupo',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 9,
            ], [
                'id'           => 139,
                'data_type_id' => 24,
                'field'        => 'mst_nivel_estudios_id',
                'type'         => 'text',
                'display_name' => 'Mst Nivel Estudios Id',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 4,
            ], [
                'id'           => 140,
                'data_type_id' => 24,
                'field'        => 'mst_area_materia_id',
                'type'         => 'text',
                'display_name' => 'Mst Area Materia Id',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 5,
            ], [
                'id'           => 141,
                'data_type_id' => 24,
                'field'        => 'mst_ensenanza_id',
                'type'         => 'text',
                'display_name' => 'Mst Ensenanza Id',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 6,
            ], [
                'id'           => 142,
                'data_type_id' => 24,
                'field'        => 'ano_ini_curso_escolar',
                'type'         => 'text',
                'display_name' => 'Ano Ini Curso Escolar',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 10,
            ], [
                'id'           => 143,
                'data_type_id' => 24,
                'field'        => 'max_acepciones_entrada',
                'type'         => 'text',
                'display_name' => 'Max Acepciones Entrada',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 11,
            ], [
                'id'           => 144,
                'data_type_id' => 24,
                'field'        => 'codigo',
                'type'         => 'text',
                'display_name' => 'Codigo',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 12,
            ], [
                'id'           => 145,
                'data_type_id' => 24,
                'field'        => 'visible_estudiante',
                'type'         => 'text',
                'display_name' => 'Visible Estudiante',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 13,
            ], [
                'id'           => 146,
                'data_type_id' => 24,
                'field'        => 'envios_habilitados',
                'type'         => 'text',
                'display_name' => 'Envios Habilitados',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 14,
            ],
            [
                'id'           => 147,
                'data_type_id' => 24,
                'field'        => 'envios_fecha_ini',
                'type'         => 'text',
                'display_name' => 'Envios Fecha Ini',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 15,
            ],
            [
                'id'           => 148,
                'data_type_id' => 24,
                'field'        => 'envios_fecha_fin',
                'type'         => 'text',
                'display_name' => 'Envios Fecha Fin',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 16,
            ],
            [
                'id'           => 149,
                'data_type_id' => 24,
                'field'        => 'estado',
                'type'         => 'text',
                'display_name' => 'Estado',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 17,
            ],
            [
                'id'           => 150,
                'data_type_id' => 24,
                'field'        => 'comentarios_visibles',
                'type'         => 'text',
                'display_name' => 'Comentarios Visibles',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 18,
            ],
            [
                'id'           => 151,
                'data_type_id' => 24,
                'field'        => 'comentarios_visibles_anteriores_a',
                'type'         => 'text',
                'display_name' => 'Comentarios Visibles Anteriores A',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 19,
            ],
            [
                'id'           => 152,
                'data_type_id' => 24,
                'field'        => 'pautas_maestras',
                'type'         => 'text',
                'display_name' => 'Pautas Maestras',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 20,
            ],
            [
                'id'           => 153,
                'data_type_id' => 24,
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 0,
                'delete'       => 1,
                'details'      => '',
                'order'        => 21,
            ],
            [
                'id'           => 154,
                'data_type_id' => 24,
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 22,
            ],
            [
                'id'           => 155,
                'data_type_id' => 24,
                'field'        => 'deleted_at',
                'type'         => 'timestamp',
                'display_name' => 'Deleted At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 23,
            ],
            [
                'id'           => 156,
                'data_type_id' => 24,
                'field'        => 'vigencia',
                'type'         => 'text',
                'display_name' => 'Vigencia',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 24,
            ],
            [
                'id'           => 157,
                'data_type_id' => 26,
                'field'        => 'id',
                'type'         => 'text',
                'display_name' => 'Id',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 1,
            ],
            [
                'id'           => 158,
                'data_type_id' => 26,
                'field'        => 'persona_id',
                'type'         => 'text',
                'display_name' => 'Persona Id',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 2,
            ],
            [
                'id'           => 159,
                'data_type_id' => 26,
                'field'        => 'titulo',
                'type'         => 'text',
                'display_name' => 'Titulo',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 3,
            ],
            [
                'id'           => 160,
                'data_type_id' => 26,
                'field'        => 'estado',
                'type'         => 'text',
                'display_name' => 'Estado',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 4,
            ],
            [
                'id'           => 161,
                'data_type_id' => 26,
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 0,
                'delete'       => 1,
                'details'      => '',
                'order'        => 5,
            ],
            [
                'id'           => 162,
                'data_type_id' => 26,
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 6,
            ],
            [
                'id'           => 163,
                'data_type_id' => 26,
                'field'        => 'deleted_at',
                'type'         => 'timestamp',
                'display_name' => 'Deleted At',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 7,
            ],
            [
                'id'           => 178,
                'data_type_id' => 30,
                'field'        => 'id',
                'type'         => 'text',
                'display_name' => 'Id',
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 1,
            ],
            [
                'id'           => 179,
                'data_type_id' => 30,
                'field'        => 'cod_centro',
                'type'         => 'text',
                'display_name' => 'Cod Centro',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 2,
            ],
            [
                'id'           => 180,
                'data_type_id' => 30,
                'field'        => 'denominacion',
                'type'         => 'text',
                'display_name' => 'Denominacion',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 3,
            ],
            [
                'id'           => 181,
                'data_type_id' => 30,
                'field'        => 'estado',
                'type'         => 'text',
                'display_name' => 'Estado',
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 4,
            ],
            [
                'id'           => 182,
                'data_type_id' => 30,
                'field'        => 'created_at',
                'type'         => 'timestamp',
                'display_name' => 'Created At',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 0,
                'delete'       => 1,
                'details'      => '',
                'order'        => 5,
            ],
            [
                'id'           => 183,
                'data_type_id' => 30,
                'field'        => 'updated_at',
                'type'         => 'timestamp',
                'display_name' => 'Updated At',
                'required'     => 0,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'details'      => '',
                'order'        => 6,
            ],
            [
                'id'           => 184,
                'data_type_id' => 30,
                'field'        => 'deleted_at',
                'type'         => 'timestamp',
                'display_name' => 'Deleted At',
                'required'     => 0,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'details'      => '',
                'order'        => 7,
            ],
        ];

        $this->command->line('Configurando permisos de accesos a tablas', 'info');
        foreach ($data_rows as $row) {
            DataRow::firstOrCreate(
                [
                    'id' => $row[
                    'id'], ],
                [
                    'data_type_id' => $row['data_type_id'],
                    'field'        => $row['field'],
                    'type'         => $row['type'],
                    'display_name' => $row['display_name'],
                    'required'     => $row['required'],
                    'browse'       => $row['browse'],
                    'read'         => $row['read'],
                    'edit'         => $row['edit'],
                    'add'          => $row['add'],
                    'delete'       => $row['delete'],
                    'details'      => $row['details'],
                    'order'        => $row['order'],
                ]
            );
        }
    }

    protected function cleanupTable($table_name)
    {
        $this->command->line("Borrando tabla {$table_name}", 'info');
        DB::table($table_name)->delete();
        $this->command->line("Reseteando autoincremental de la tabla {$table_name}", 'info');
        DB::statement('SET @count = 0;');
        DB::statement("UPDATE `{$table_name}` SET `{$table_name}`.`id` = @count:= @count + 1;");
        DB::statement("ALTER TABLE `{$table_name}` AUTO_INCREMENT = 1;");
    }

    private function cleanTable($name)
    {
        try {
            $this->cleanupTable($name);
        } catch (\Throwable $th) {
            $this->command->line($th->getMessage(), 'error');
        }
    }

    private function reinstallControlPanel()
    {
        $this->command->line('Cargando configuración del panel de control', 'info');
        Artisan::call('db:seed --class=VoyagerDatabaseSeeder --force');
        $this->command->line('FIN VOGAGER DATABAS SEEDER', 'info');
    }

    private function setPermissionsRoles()
    {
        $permissions = [
            ['id' => '1', 'key' => 'browse_admin', 'table_name' => null],
            ['id' => '2', 'key' => 'browse_bread', 'table_name' => null],
            ['id' => '3', 'key' => 'browse_database', 'table_name' => null],
            ['id' => '4', 'key' => 'browse_media', 'table_name' => null],
            ['id' => '5', 'key' => 'browse_compass', 'table_name' => null],
            ['id' => '26', 'key' => 'browse_hooks', 'table_name' => null],
        ];

        $this->command->line('Configurando permisos', 'info');
        foreach ($permissions as $permiso) {
            Permission::firstOrCreate(
                [
                    'id' => $permiso['id'], ],
                [
                    'key'        => $permiso['key'],
                    'table_name' => $permiso['table_name'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        Permission::generateFor('menus');
        Permission::generateFor('roles');
        Permission::generateFor('users');
        Permission::generateFor('settings');
        Permission::generateFor('audits_eventos');
        Permission::generateFor('audits_eventos_tipos');
        Permission::generateFor('audits');

        // todos los permisos a admin
        $role        = Role::where('name', 'admin')->firstOrFail();
        $permissions = Permission::all();
        $role->permissions()->sync(
            $permissions->pluck('id')->all()
        );

        $role_user_id = Role::where('name', 'user')->firstOrFail()->id;

        // permisos para el usuario
        $permisos_user = [
            'browse_admin',
            'browse_compass',
            'browse_audits_eventos',
            'read_audits_eventos',
            'browse_audits_eventos_tipos',
            'read_audits_eventos_tipos',
            'browse_audits',
            'read_audits',
        ];

        $this->command->line('Configurando permisos de los roles', 'info');
        foreach ($permisos_user as $p) {
            $permiso = Permission::where('key', $p)->firstOrFail();
            PermissionRole::firstOrCreate(
                [
                    'permission_id' => $permiso['id'],
                    'role_id'       => $role_user_id,
                ]
            );
        }
    }

    private function createUser($name, $email, $rol = 'user')
    {
        $this->command->line("Creando usuario {$name} {$rol}", 'info');
        $role = Role::where('name', $rol)->firstOrFail();

        return User::firstOrCreate(
            ['name' => $name],
            [
                'email'          => $email,
                'password'       => bcrypt('12345678'),
                'remember_token' => Str::random(60),
                'role_id'        => $role->id,
                'updated_at'     => now(),
            ]
        );
    }

    private function createMenus()
    {
        $this->call(MenusTableSeeder::class);
        $this->call(MenuItemsTableSeeder::class);

        return;
        // antiguo seeder
        $menuAdmin = Menu::firstOrCreate([
            'name' => 'admin',
        ]);

        // Borrar menu admin actual
        // $itemsAdmin = MenuItem::where('menu_id', $menuAdmin->id );
        // foreach ($itemsAdmin as $itm ) {
        //     $itm->delete();
        // }

        // |id |menu_id|title             |icon_class      |parent_id|order||route                 |
        // |---|-------|------------------|----------------|---------|-----||----------------------|
        // |1  |1      |Tablero           |voyager-boat    |         |1    ||voyager.dashboard     |
        // |2  |1      |Multimedia        |voyager-images  |         |5    ||voyager.media.index   |
        // |3  |1      |Usuarios          |voyager-person  |         |3    ||voyager.users.index   |
        // |4  |1      |Roles             |voyager-lock    |         |2    ||voyager.roles.index   |
        // |5  |1      |Herramientas      |voyager-tools   |         |9    ||                      |
        // |6  |1      |Diseñador de Menús|voyager-list    |5        |10   ||voyager.menus.index   |
        // |7  |1      |Base de Datos     |voyager-data    |5        |11   ||voyager.database.index|
        // |8  |1      |Compás            |voyager-compass |5        |12   ||voyager.compass.index |
        // |9  |1      |BREAD             |voyager-bread   |5        |13   ||voyager.bread.index   |
        // |10 |1      |Parámetros        |voyager-settings|         |14   ||voyager.settings.index|

        $this->command->line('Configurando menú para el superadmin', 'info');
        $menu_admin_items = [
            [
                'title'      => 'Tablero',
                'icon_class' => 'voyager-boat',
                'order'      => '1',
                'route'      => 'voyager.dashboard',
                'target'     => '_self',
            ],
            [
                'title'      => 'Logs',
                'target'     => '_self',
                'icon_class' => 'voyager-warning',
                'color'      => '#000000',
                'parent_id'  => null,
                'route'      => 'logs.view',
            ],
            [
                'title'      => 'Multimedia',
                'icon_class' => 'voyager-images',
                'order'      => '5',
                'route'      => 'voyager.media.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'Usuarios',
                'icon_class' => 'voyager-person',
                'parent_id'  => null,
                'order'      => '3',
                'route'      => 'voyager.users.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'Roles',
                'icon_class' => 'voyager-lock',
                'parent_id'  => null,
                'order'      => '2',
                'route'      => 'voyager.roles.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'Herramientas',
                'icon_class' => 'voyager-tools',
                'order'      => '9',
                'route'      => '',
                'target'     => '_self',
            ],
            [
                'title'      => 'Diseñador de Menús',
                'icon_class' => 'voyager-list',
                'parent_id'  => '5',
                'order'      => '10',
                'route'      => 'voyager.menus.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'Base de Datos',
                'icon_class' => 'voyager-data',
                'parent_id'  => '5',
                'order'      => '11',
                'route'      => 'voyager.database.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'BREAD',
                'icon_class' => 'voyager-bread',
                'parent_id'  => '5',
                'order'      => '13',
                'route'      => 'voyager.bread.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'Parámetros',
                'icon_class' => 'voyager-settings',
                'order'      => '14',
                'route'      => 'voyager.settings.index',
                'target'     => '_self',
            ],
            [
                'title'      => 'Vigencia',
                'icon_class' => 'voyager-calendar',
                'order'      => '14',
                'route'      => 'vigencia',
                'target'     => '_self',
            ],

            // array('title'=> 'Compás','icon_class'=>'voyager-compass' ,'parent_id'=>'5','order'=>'12','route' => 'voyager.compass.index', 'target' => '_self'),
            // no va audits
            [
                'title'      => 'Audits',
                'url'        => '',
                'target'     => '_self',
                'icon_class' => 'voyager-search',
                'color'      => '#000000',
                'parent_id'  => null,
                'order'      => '2',
                'created_at' => '2020-09-25 11:33:12',
                'updated_at' => '2020-09-25 11:33:31',
                'route'      => 'voyager.audits.index',
                'parameters' => null,
            ],
        ];

        $this->command->line("\nCreando menu admin: ", 'info');

        foreach ($menu_admin_items as $itm) {
            $this->command->line('Creando item menu admin: '.$itm['title'], 'info');
            $this->command->line('route'.$itm['route'], 'info');

            MenuItem::firstOrCreate(
                ['title' => $itm['title']],
                [
                    'menu_id'    => $menuAdmin['id'],
                    'target'     => $itm['target'] ?? '_self',
                    'icon_class' => $itm['icon_class'] ?? 'voyager-list',
                    // 'color'         => $itm['color']??'#000',
                    'parent_id' => $itm['parent_id'] ?? null,
                    'order'     => $itm['order'] ?? '100',
                    'route'     => $itm['route'],
                    'url'       => $itm['url'] ?? '',
                ]
            );
        }

        // Menus
        $menu = Menu::firstOrCreate([
            'name' => 'Oficina técnica',
        ]);

        $this->command->line("\nConfigurando menú para el usuario oficina técnica", 'info');
        $menu_items = [
            // array('title' => 'Audits Eventos Apis','url' => '','target' => '_self','icon_class' => 'voyager-logbook','color' => '#000000','parent_id' => NULL,'order' => '5','created_at' => '2020-09-21 11:53:14','updated_at' => '2020-09-25 11:33:40','route' => 'voyager.audits-eventos-apis.index','parameters' => 'null'),
            ['title' => 'Logs', 'target' => '_self', 'icon_class' => 'voyager-warning', 'color' => '#000000', 'parent_id' => null, 'order' => '1', 'created_at' => '2020-09-21 12:30:17', 'updated_at' => '2020-09-25 11:33:18', 'route' => 'logs.view', 'parameters' => 'null'],

            // array('title'=> 'Multimedia','icon_class'=>'voyager-images' ,'order'=>'5' ,'route' => 'voyager.media.index', 'target' => '_self'), // faltan permisos

            // array('title'=> 'Herramientas','icon_class'=>'voyager-tools' ,'order'=>'9' ,'route' => '', 'target' => '_self'),
            // array('title'=> 'Compás','icon_class'=>'voyager-compass' ,'parent_id'=>'5','order'=>'12','route' => 'voyager.compass.index', 'target' => '_self'),

            // array('title'=> 'Parámetros','icon_class'=>'voyager-settings','order'=>'14','route' => 'voyager.settings.index', 'target' => '_self'), // falta permisos para user

            ['title' => 'Vigencia', 'icon_class' => 'voyager-calendar', 'order' => '14', 'route' => 'vigencia', 'target' => '_self'],

            // array('title' => 'Audits Eventos','url' => '','target' => '_self','icon_class' => 'voyager-logbook','color' => '#000000','parent_id' => NULL,'order' => '4','created_at' => '2020-09-25 11:32:23','updated_at' => '2020-09-25 11:33:40','route' => 'voyager.audits-eventos.index','parameters' => NULL),
            // array('title' => 'Audits Eventos Tipos','url' => '','target' => '_self','icon_class' => 'voyager-tag','color' => '#000000','parent_id' => NULL,'order' => '3','created_at' => '2020-09-25 11:32:47','updated_at' => '2020-09-25 11:33:34','route' => 'voyager.audits-eventos-tipos.index','parameters' => NULL),
            ['title' => 'Audits', 'url' => '', 'target' => '_self', 'icon_class' => 'voyager-search', 'color' => '#000000', 'parent_id' => null, 'order' => '2', 'created_at' => '2020-09-25 11:33:12', 'updated_at' => '2020-09-25 11:33:31', 'route' => 'voyager.audits.index', 'parameters' => null],

            // array('title' => 'Centros Usuarios','url' => '','target' => '_self','icon_class' => 'voyager-company','color' => '#000000','parent_id' => NULL,'order' => '19','created_at' => '2020-10-07 08:44:06','updated_at' => '2020-10-07 08:45:25','route' => 'voyager.centros-usuarios.index','parameters' => 'null'),
            // array('title' => 'Centros Autorizados','url' => '','target' => '_self','icon_class' => 'voyager-company','color' => '#000000','parent_id' => NULL,'order' => '20','created_at' => '2020-10-07 08:46:05','updated_at' => '2020-10-07 08:46:05','route' => 'voyager.centros-autorizados.index','parameters' => 'null'),
            // array('title' => 'Aulas Participantes','url' => '','target' => '_self','icon_class' => 'voyager-people','color' => '#000000','parent_id' => NULL,'order' => '21','created_at' => '2020-10-07 08:47:40','updated_at' => '2020-10-07 08:47:40','route' => 'voyager.aulas-participantes.index','parameters' => 'null'),
            // array('title' => 'Aulas Smart','url' => '','target' => '_self','icon_class' => 'voyager-people','color' => '#000000','parent_id' => NULL,'order' => '22','created_at' => '2020-10-07 08:48:29','updated_at' => '2020-10-07 08:48:29','route' => 'voyager.aulas-smart.index','parameters' => 'null')
        ];

        foreach ($menu_items as $menu_item) {
            $this->command->line('Creando item menu OT: '.$menu['id'].' t:'.$menu_item['title'], 'info');
            MenuItem::firstOrCreate(
                [
                    'title'   => $menu_item['title'],
                    'menu_id' => $menu['id'],
                ],
                [
                    'menu_id'    => $menu['id'],
                    'url'        => $menu_item['url'] ?? null,
                    'target'     => $menu_item['target'],
                    'icon_class' => $menu_item['icon_class'],
                    'color'      => $menu_item['color'] ?? null,
                    'parent_id'  => $menu_item['parent_id'] ?? null,
                    'order'      => $menu_item['order'],
                    'route'      => $menu_item['route'],
                ]
            );
        }
    }

    private function setDefaultSettigns()
    {
        $settings = [
            [
                'key'          => 'site.title',
                'display_name' => 'Título del sitio',
                'value'        => 'Lexicán',
            ],
            [
                'key'          => 'admin.title',
                'display_name' => 'Título del administrador',
                'value'        => 'Panel de control',
            ],
            [
                'key'          => 'admin.description',
                'display_name' => 'Descripción del administrador',
                'value'        => 'Bienvenido al panel de control',
            ],
        ];

        foreach ($settings as $s) {
            Setting::updateOrCreate(
                ['key' => $s['key']],
                ['display_name' => $s['display_name']],
                ['value'        => $s['value']]
            );
        }
    }
}
