# Imagen base de la que partimos.
FROM php:8.1-apache

# UPLOAD_MAXSIZE DEBERIA CAMBIAR EL MAXIMO DE ARCHIVO ENVIABLE EN PHP INI
# Se crean las variables de entorno para el direcotrio raiz de apache y el usuario (para darle permisos)
ENV APACHE_DOCUMENT_ROOT=/var/www/html
ENV UID=33
ENV GID=0

ENV LOCATION=/medusa/apps/lexican
ENV PORT=8083
ENV PORTSSL=8448

WORKDIR $APACHE_DOCUMENT_ROOT
RUN mkdir -p $LOCATION
ENV SRVDIR=${APACHE_DOCUMENT_ROOT}${LOCATION}
WORKDIR $SRVDIR

# Actualizamos fuentes apt get y
# Instalamos los paquetes necesarios en la imagen
    # git \

RUN apt-get update && apt-get install -y \
    zip \
    sudo \
    curl \
    unzip \
    libzip-dev \
    libonig-dev \
    libicu-dev \
    libbz2-dev \
    libpng-dev \
    libjpeg-dev \
    libmcrypt-dev \
    libreadline-dev \
    libfreetype6-dev \
    g++ \
    vim \
    nano \
    libwebp-dev \
    libjpeg62-turbo-dev \
    libxpm-dev \
    ffmpeg \
    libxslt-dev \
    tzdata

# Se configura apache
RUN sed -i 's/80/${PORT}/' /etc/apache2/ports.conf && \
    sed -i 's/443/${PORTSSL}/' /etc/apache2/ports.conf && \
    sed -i 's/*:80/*:${PORT}/' /etc/apache2/sites-available/000-default.conf && \
    sed -i 's/*:443/*:${PORTSSL}/' /etc/apache2/sites-available/default-ssl.conf && \
    sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf && \
    sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Se activa el módulo de reescritura de apache, el headers y el ssl
RUN a2enmod rewrite headers ssl

RUN printf "post_max_size=$UPLOAD_MAXSIZE \nupload_max_filesize=$UPLOAD_MAXSIZE \n" >> $PHP_INI_DIR/php.ini-development

# Se configura php
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# Se configura la instalación de la extensión gd de php
RUN docker-php-ext-configure gd \
    --enable-gd \
    --with-webp \
    --with-jpeg \
    --with-xpm \
    --with-freetype

# Se instalan las dependencias de php
RUN docker-php-ext-install \
    bz2 \
    intl \
    iconv \
    bcmath \
    opcache \
    calendar \
    mbstring \
    pdo_mysql \
    zip \
    gd \
    xsl \
    exif

# Se habilita la extensión exif
# Salta un warning:exif.so alrready loaded! creo que se podria borrar esta linea
# RUN docker-php-ext-enable exif

# Se instala composer
COPY --from=composer:2.4 /usr/bin/composer /usr/bin/composer


# Se añade el usuario al grupo root y al grupo de apache
# RUN useradd -G www-data,root -s /bin/bash -u ${UID} -d /home/devuser devuser
# RUN mkdir -p /home/devuser/.composer && \
#     chown -R devuser:devuser /home/devuser 
# RUN echo 'devuser:Clave@#$%' | chpasswd


RUN apt-get autoremove -y

# --chmod requiere buildkit , ejecuta docker build como `docker buildx build`
# o como  `DOCKER_BUILDKIT=1 docker build`
# Copiamos el código del proyecto a la carpeta del host de apache
COPY --chown=${UID}:${GID} --chmod=0775  src "$SRVDIR"

ARG APP_VERSION
ENV APP_VERSION=$APP_VERSION

#RUN sed -i -e "s/APP_VERSION=.*/APP_VERSION=\"`ECHO $APP_VERSION` `date`\"/" .env

# Borramos el posible link simbólico de public a storage
RUN rm -fR $SRVDIR/public/storage

# Creamos un nuevo link simbólico teniendo en cuenta la ruta del contenedor
RUN ln -s $SRVDIR/storage/app/public/ $SRVDIR/public/storage

# Otorgamos permisos a la carpeta
 RUN chmod -R 770 $SRVDIR/storage 


RUN chmod -R 770 $SRVDIR/bootstrap
# RUN chmod -R 770 $SRVDIR/storage/app/public
RUN chmod -R 770 $SRVDIR/storage/framework/cache
RUN chmod -R 770 $SRVDIR/storage/framework/*
RUN chmod -R 770 $SRVDIR/storage/logs

# RUN echo "`date` $TZ " > $SRVDIR/public/imgcreation.html
RUN echo `date` > $SRVDIR/public/imgcreation.html
RUN echo "version" >> $SRVDIR/public/imgcreation.html
RUN echo $APP_VERSION >> $SRVDIR/public/imgcreation.html


# Exponemos el puerto 8081 y el 8448
EXPOSE ${PORT}/tcp ${PORTSSL}/tcp
