import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { MediaStorage } from '@lexican/app';

/** Keys are generated by the media service (`<uuid>.<ext>`); anything else is refused (no path traversal). */
const KEY = /^[0-9a-f-]{36}\.[a-z0-9]+$/;

function pathFor(root: string, key: string): string {
  if (!KEY.test(key)) throw new Error('Invalid media storage key');
  return join(root, key.slice(0, 2), key);
}

/** Filesystem storage, sharded by the first two characters of the key; writes are atomic (temp + rename). */
export function fsMediaStorage(root: string): MediaStorage {
  return {
    async put(key, bytes) {
      const target = pathFor(root, key);
      await mkdir(join(root, key.slice(0, 2)), { recursive: true, mode: 0o750 });
      const tmp = `${target}.${process.pid}.${Date.now()}.tmp`;
      await writeFile(tmp, bytes, { mode: 0o640, flag: 'wx' });
      await rename(tmp, target);
    },
    async get(key) {
      try {
        return new Uint8Array(await readFile(pathFor(root, key)));
      } catch (e) {
        if ((e as NodeJS.ErrnoException).code === 'ENOENT') return null;
        throw e;
      }
    },
  };
}
