import { openAsBlob } from 'node:fs';
import { mkdir, readdir, rename, rm, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { MediaStorage } from '@lexican/app';

/** Keys are generated by the media service (`<uuid>.<ext>`); anything else is refused (no path traversal). */
const KEY = /^[0-9a-f-]{36}\.[a-z0-9]+$/;

function pathFor(root: string, key: string): string {
  if (!KEY.test(key)) throw new Error('Invalid media storage key');
  return join(root, key.slice(0, 2), key);
}

const isMissing = (e: unknown) => (e as NodeJS.ErrnoException).code === 'ENOENT';

/**
 * Filesystem storage on the media volume, sharded by the first two characters of the key. Writes are atomic
 * (exclusive temp file + rename); reads are lazy Blobs (`openAsBlob`), so ranges and streaming never load the
 * whole file into memory.
 */
export function fsMediaStorage(root: string): MediaStorage {
  return {
    async put(key, bytes) {
      const target = pathFor(root, key);
      await mkdir(join(root, key.slice(0, 2)), { recursive: true, mode: 0o750 });
      const tmp = `${target}.${process.pid}.${Date.now()}.tmp`;
      try {
        await writeFile(tmp, bytes, { mode: 0o640, flag: 'wx' });
        await rename(tmp, target);
      } catch (e) {
        await rm(tmp, { force: true });
        throw e;
      }
    },
    async open(key) {
      const path = pathFor(root, key);
      // stat first: for a missing file openAsBlob throws ENOENT on macOS but ERR_INVALID_ARG_VALUE on Linux.
      try {
        if (!(await stat(path)).isFile()) return null;
      } catch (e) {
        if (isMissing(e)) return null;
        throw e;
      }
      return openAsBlob(path);
    },
    async delete(key) {
      await rm(pathFor(root, key), { force: true });
    },
    async keys() {
      const shards = await readdir(root).catch((e: unknown) =>
        isMissing(e) ? [] : Promise.reject(e),
      );
      const out: string[] = [];
      for (const s of shards) {
        if (!/^[0-9a-f]{2}$/.test(s)) continue;
        for (const f of await readdir(join(root, s))) if (KEY.test(f)) out.push(f);
      }
      return out;
    },
  };
}
